package Tablero;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aaronmoreno
 */
public class TableroDamasInglesas extends javax.swing.JFrame {

    /**
     * Creates new form TableroDamasInglesas
     */
    public TableroDamasInglesas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        A70 = new javax.swing.JButton();
        A60 = new javax.swing.JButton();
        A50 = new javax.swing.JButton();
        A40 = new javax.swing.JButton();
        A30 = new javax.swing.JButton();
        A20 = new javax.swing.JButton();
        A10 = new javax.swing.JButton();
        A00 = new javax.swing.JButton();
        B71 = new javax.swing.JButton();
        B61 = new javax.swing.JButton();
        B51 = new javax.swing.JButton();
        B41 = new javax.swing.JButton();
        B31 = new javax.swing.JButton();
        B21 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B01 = new javax.swing.JButton();
        C52 = new javax.swing.JButton();
        C42 = new javax.swing.JButton();
        C32 = new javax.swing.JButton();
        C22 = new javax.swing.JButton();
        C12 = new javax.swing.JButton();
        C02 = new javax.swing.JButton();
        D73 = new javax.swing.JButton();
        D63 = new javax.swing.JButton();
        D53 = new javax.swing.JButton();
        D43 = new javax.swing.JButton();
        D33 = new javax.swing.JButton();
        D23 = new javax.swing.JButton();
        D13 = new javax.swing.JButton();
        D03 = new javax.swing.JButton();
        E74 = new javax.swing.JButton();
        E64 = new javax.swing.JButton();
        E54 = new javax.swing.JButton();
        E44 = new javax.swing.JButton();
        E34 = new javax.swing.JButton();
        E24 = new javax.swing.JButton();
        E14 = new javax.swing.JButton();
        E04 = new javax.swing.JButton();
        F75 = new javax.swing.JButton();
        F65 = new javax.swing.JButton();
        F55 = new javax.swing.JButton();
        F45 = new javax.swing.JButton();
        F35 = new javax.swing.JButton();
        F25 = new javax.swing.JButton();
        F15 = new javax.swing.JButton();
        F05 = new javax.swing.JButton();
        G76 = new javax.swing.JButton();
        G66 = new javax.swing.JButton();
        G56 = new javax.swing.JButton();
        G46 = new javax.swing.JButton();
        G36 = new javax.swing.JButton();
        G26 = new javax.swing.JButton();
        G16 = new javax.swing.JButton();
        G06 = new javax.swing.JButton();
        H77 = new javax.swing.JButton();
        H67 = new javax.swing.JButton();
        H57 = new javax.swing.JButton();
        H47 = new javax.swing.JButton();
        H37 = new javax.swing.JButton();
        H27 = new javax.swing.JButton();
        H17 = new javax.swing.JButton();
        H07 = new javax.swing.JButton();
        C72 = new javax.swing.JButton();
        C62 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);

        A70.setBackground(new java.awt.Color(120, 76, 62));
        A70.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A70.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        A70.setToolTipText("");
        A70.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A70.setOpaque(true);
        A70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A70ActionPerformed(evt);
            }
        });

        A60.setBackground(new java.awt.Color(219, 179, 138));
        A60.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A60.setOpaque(true);
        A60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A60ActionPerformed(evt);
            }
        });

        A50.setBackground(new java.awt.Color(120, 76, 62));
        A50.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        A50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A50.setOpaque(true);
        A50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A50ActionPerformed(evt);
            }
        });

        A40.setBackground(new java.awt.Color(219, 179, 138));
        A40.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A40.setOpaque(true);
        A40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A40ActionPerformed(evt);
            }
        });

        A30.setBackground(new java.awt.Color(120, 76, 62));
        A30.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A30.setOpaque(true);
        A30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A30ActionPerformed(evt);
            }
        });

        A20.setBackground(new java.awt.Color(219, 179, 138));
        A20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A20.setOpaque(true);
        A20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A20ActionPerformed(evt);
            }
        });

        A10.setBackground(new java.awt.Color(120, 76, 62));
        A10.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        A10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A10.setOpaque(true);
        A10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A10ActionPerformed(evt);
            }
        });

        A00.setBackground(new java.awt.Color(219, 179, 138));
        A00.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A00.setOpaque(true);
        A00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A00ActionPerformed(evt);
            }
        });

        B71.setBackground(new java.awt.Color(219, 179, 138));
        B71.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B71.setOpaque(true);
        B71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B71ActionPerformed(evt);
            }
        });

        B61.setBackground(new java.awt.Color(120, 76, 62));
        B61.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        B61.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B61.setOpaque(true);
        B61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B61ActionPerformed(evt);
            }
        });

        B51.setBackground(new java.awt.Color(219, 179, 138));
        B51.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B51.setOpaque(true);
        B51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B51ActionPerformed(evt);
            }
        });

        B41.setBackground(new java.awt.Color(120, 76, 62));
        B41.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B41.setOpaque(true);
        B41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B41ActionPerformed(evt);
            }
        });

        B31.setBackground(new java.awt.Color(219, 179, 138));
        B31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B31.setOpaque(true);
        B31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B31ActionPerformed(evt);
            }
        });

        B21.setBackground(new java.awt.Color(120, 76, 62));
        B21.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        B21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B21.setOpaque(true);
        B21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B21ActionPerformed(evt);
            }
        });

        B11.setBackground(new java.awt.Color(219, 179, 138));
        B11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B11.setOpaque(true);
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });

        B01.setBackground(new java.awt.Color(120, 76, 62));
        B01.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        B01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B01.setOpaque(true);
        B01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B01ActionPerformed(evt);
            }
        });

        C52.setBackground(new java.awt.Color(120, 76, 62));
        C52.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        C52.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C52.setOpaque(true);
        C52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C52ActionPerformed(evt);
            }
        });

        C42.setBackground(new java.awt.Color(219, 179, 138));
        C42.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C42.setOpaque(true);
        C42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C42ActionPerformed(evt);
            }
        });

        C32.setBackground(new java.awt.Color(120, 76, 62));
        C32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C32.setOpaque(true);
        C32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C32ActionPerformed(evt);
            }
        });

        C22.setBackground(new java.awt.Color(219, 179, 138));
        C22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C22.setOpaque(true);
        C22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C22ActionPerformed(evt);
            }
        });

        C12.setBackground(new java.awt.Color(120, 76, 62));
        C12.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        C12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C12.setOpaque(true);
        C12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C12ActionPerformed(evt);
            }
        });

        C02.setBackground(new java.awt.Color(219, 179, 138));
        C02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C02.setOpaque(true);
        C02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C02ActionPerformed(evt);
            }
        });

        D73.setBackground(new java.awt.Color(219, 179, 138));
        D73.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D73.setOpaque(true);
        D73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D73ActionPerformed(evt);
            }
        });

        D63.setBackground(new java.awt.Color(120, 76, 62));
        D63.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        D63.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D63.setOpaque(true);
        D63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D63ActionPerformed(evt);
            }
        });

        D53.setBackground(new java.awt.Color(219, 179, 138));
        D53.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D53.setOpaque(true);
        D53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D53ActionPerformed(evt);
            }
        });

        D43.setBackground(new java.awt.Color(120, 76, 62));
        D43.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D43.setOpaque(true);
        D43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D43ActionPerformed(evt);
            }
        });

        D33.setBackground(new java.awt.Color(219, 179, 138));
        D33.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D33.setOpaque(true);
        D33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D33ActionPerformed(evt);
            }
        });

        D23.setBackground(new java.awt.Color(120, 76, 62));
        D23.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        D23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D23.setOpaque(true);
        D23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D23ActionPerformed(evt);
            }
        });

        D13.setBackground(new java.awt.Color(219, 179, 138));
        D13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D13.setOpaque(true);
        D13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D13ActionPerformed(evt);
            }
        });

        D03.setBackground(new java.awt.Color(120, 76, 62));
        D03.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        D03.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D03.setOpaque(true);
        D03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D03ActionPerformed(evt);
            }
        });

        E74.setBackground(new java.awt.Color(120, 76, 62));
        E74.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        E74.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E74.setOpaque(true);
        E74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E74ActionPerformed(evt);
            }
        });

        E64.setBackground(new java.awt.Color(219, 179, 138));
        E64.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E64.setOpaque(true);
        E64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E64ActionPerformed(evt);
            }
        });

        E54.setBackground(new java.awt.Color(120, 76, 62));
        E54.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        E54.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E54.setOpaque(true);
        E54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E54ActionPerformed(evt);
            }
        });

        E44.setBackground(new java.awt.Color(219, 179, 138));
        E44.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E44.setOpaque(true);
        E44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E44ActionPerformed(evt);
            }
        });

        E34.setBackground(new java.awt.Color(120, 76, 62));
        E34.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E34.setOpaque(true);
        E34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E34ActionPerformed(evt);
            }
        });

        E24.setBackground(new java.awt.Color(219, 179, 138));
        E24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E24.setOpaque(true);
        E24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E24ActionPerformed(evt);
            }
        });

        E14.setBackground(new java.awt.Color(120, 76, 62));
        E14.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        E14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E14.setOpaque(true);
        E14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E14ActionPerformed(evt);
            }
        });

        E04.setBackground(new java.awt.Color(219, 179, 138));
        E04.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E04.setOpaque(true);
        E04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E04ActionPerformed(evt);
            }
        });

        F75.setBackground(new java.awt.Color(219, 179, 138));
        F75.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F75.setOpaque(true);
        F75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F75ActionPerformed(evt);
            }
        });

        F65.setBackground(new java.awt.Color(120, 76, 62));
        F65.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        F65.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F65.setOpaque(true);
        F65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F65ActionPerformed(evt);
            }
        });

        F55.setBackground(new java.awt.Color(219, 179, 138));
        F55.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F55.setOpaque(true);
        F55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F55ActionPerformed(evt);
            }
        });

        F45.setBackground(new java.awt.Color(120, 76, 62));
        F45.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F45.setOpaque(true);
        F45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F45ActionPerformed(evt);
            }
        });

        F35.setBackground(new java.awt.Color(219, 179, 138));
        F35.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F35.setOpaque(true);
        F35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F35ActionPerformed(evt);
            }
        });

        F25.setBackground(new java.awt.Color(120, 76, 62));
        F25.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        F25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F25.setOpaque(true);
        F25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F25ActionPerformed(evt);
            }
        });

        F15.setBackground(new java.awt.Color(219, 179, 138));
        F15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F15.setOpaque(true);
        F15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F15ActionPerformed(evt);
            }
        });

        F05.setBackground(new java.awt.Color(120, 76, 62));
        F05.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        F05.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F05.setOpaque(true);
        F05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F05ActionPerformed(evt);
            }
        });

        G76.setBackground(new java.awt.Color(120, 76, 62));
        G76.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        G76.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G76.setOpaque(true);
        G76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G76ActionPerformed(evt);
            }
        });

        G66.setBackground(new java.awt.Color(219, 179, 138));
        G66.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G66.setOpaque(true);
        G66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G66ActionPerformed(evt);
            }
        });

        G56.setBackground(new java.awt.Color(120, 76, 62));
        G56.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        G56.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G56.setOpaque(true);
        G56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G56ActionPerformed(evt);
            }
        });

        G46.setBackground(new java.awt.Color(219, 179, 138));
        G46.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G46.setOpaque(true);
        G46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G46ActionPerformed(evt);
            }
        });

        G36.setBackground(new java.awt.Color(120, 76, 62));
        G36.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G36.setOpaque(true);
        G36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G36ActionPerformed(evt);
            }
        });

        G26.setBackground(new java.awt.Color(219, 179, 138));
        G26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G26.setOpaque(true);
        G26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G26ActionPerformed(evt);
            }
        });

        G16.setBackground(new java.awt.Color(120, 76, 62));
        G16.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        G16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G16.setOpaque(true);
        G16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G16ActionPerformed(evt);
            }
        });

        G06.setBackground(new java.awt.Color(219, 179, 138));
        G06.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G06.setOpaque(true);
        G06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G06ActionPerformed(evt);
            }
        });

        H77.setBackground(new java.awt.Color(219, 179, 138));
        H77.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H77.setOpaque(true);
        H77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H77ActionPerformed(evt);
            }
        });

        H67.setBackground(new java.awt.Color(120, 76, 62));
        H67.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        H67.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H67.setOpaque(true);
        H67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H67ActionPerformed(evt);
            }
        });

        H57.setBackground(new java.awt.Color(219, 179, 138));
        H57.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H57.setOpaque(true);
        H57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H57ActionPerformed(evt);
            }
        });

        H47.setBackground(new java.awt.Color(120, 76, 62));
        H47.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H47.setOpaque(true);
        H47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H47ActionPerformed(evt);
            }
        });

        H37.setBackground(new java.awt.Color(219, 179, 138));
        H37.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H37.setOpaque(true);
        H37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H37ActionPerformed(evt);
            }
        });

        H27.setBackground(new java.awt.Color(120, 76, 62));
        H27.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        H27.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H27.setOpaque(true);
        H27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H27ActionPerformed(evt);
            }
        });

        H17.setBackground(new java.awt.Color(219, 179, 138));
        H17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H17.setOpaque(true);
        H17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H17ActionPerformed(evt);
            }
        });

        H07.setBackground(new java.awt.Color(120, 76, 62));
        H07.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Rojas.png")); // NOI18N
        H07.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H07.setOpaque(true);
        H07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H07ActionPerformed(evt);
            }
        });

        C72.setBackground(new java.awt.Color(120, 76, 62));
        C72.setIcon(new javax.swing.ImageIcon("/Volumes/YianMM/Cajon de codigos/Java/TAP/Primera unidad/DamasIng_Def/JuegoDeMesaInglesas/src/Imagenes/Negras.png")); // NOI18N
        C72.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C72.setOpaque(true);
        C72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C72ActionPerformed(evt);
            }
        });

        C62.setBackground(new java.awt.Color(219, 179, 138));
        C62.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C62.setOpaque(true);
        C62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C62ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A50, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B51, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C52, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D53, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E54, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F55, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(G56, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H57, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A40, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B41, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C42, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D43, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E44, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F45, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G46, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H47, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B61, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C62, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D63, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E64, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F65, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G66, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H67, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B71, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C72, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D73, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E74, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F75, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G76, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H77, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F25, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(G26, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H27, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A00, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B01, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C02, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D03, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E04, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F05, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(G06, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H07, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(G16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C32, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D33, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E34, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F35, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(G36, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H37, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(A60, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A70, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A00, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B01, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C02, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(D03, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(E04, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(F05, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(G06, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(H07, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F25, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G26, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H27, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C32, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D33, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E34, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F35, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G36, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H37, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A40, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B41, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C42, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D43, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E44, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F45, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G46, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H47, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A50, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B51, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C52, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D53, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E54, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F55, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G56, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H57, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A60, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B61, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C62, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D63, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E64, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F65, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G66, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H67, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A70, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B71, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C72, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D73, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E74, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F75, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G76, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H77, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B61ActionPerformed

    private void F65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F65ActionPerformed

    private void A00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A00ActionPerformed

    private void A10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A10ActionPerformed

    private void A20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A20ActionPerformed

    private void A30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A30ActionPerformed

    private void A40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A40ActionPerformed

    private void A50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A50ActionPerformed

    private void A60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A60ActionPerformed

    private void A70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A70ActionPerformed

    private void B01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B01ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B11ActionPerformed

    private void B21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B21ActionPerformed

    private void B31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B31ActionPerformed

    private void B41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B41ActionPerformed

    private void B51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B51ActionPerformed

    private void B71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B71ActionPerformed

    private void C02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C02ActionPerformed

    private void C12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C12ActionPerformed

    private void C22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C22ActionPerformed

    private void C32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C32ActionPerformed

    private void C42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C42ActionPerformed

    private void C52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C52ActionPerformed

    private void C62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C62ActionPerformed

    private void C72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C72ActionPerformed

    private void D03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D03ActionPerformed

    private void D13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D13ActionPerformed

    private void D23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D23ActionPerformed

    private void D33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D33ActionPerformed

    private void D43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D43ActionPerformed

    private void D53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D53ActionPerformed

    private void D63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D63ActionPerformed

    private void D73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D73ActionPerformed

    private void E04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E04ActionPerformed

    private void E14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E14ActionPerformed

    private void E24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E24ActionPerformed

    private void E34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E34ActionPerformed

    private void E44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E44ActionPerformed

    private void E54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E54ActionPerformed

    private void E64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E64ActionPerformed

    private void E74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E74ActionPerformed

    private void F05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F05ActionPerformed

    private void F15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F15ActionPerformed

    private void F25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F25ActionPerformed

    private void F35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F35ActionPerformed

    private void F45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F45ActionPerformed

    private void F55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F55ActionPerformed

    private void F75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F75ActionPerformed

    private void G06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G06ActionPerformed

    private void G16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G16ActionPerformed

    private void G26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G26ActionPerformed

    private void G36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G36ActionPerformed

    private void G46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G46ActionPerformed

    private void G56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G56ActionPerformed

    private void G66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G66ActionPerformed

    private void G76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G76ActionPerformed

    private void H07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H07ActionPerformed

    private void H17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H17ActionPerformed

    private void H27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H27ActionPerformed

    private void H37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H37ActionPerformed

    private void H47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H47ActionPerformed

    private void H57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H57ActionPerformed

    private void H67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H67ActionPerformed

    private void H77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H77ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton A00;
    public static javax.swing.JButton A10;
    public static javax.swing.JButton A20;
    public static javax.swing.JButton A30;
    public static javax.swing.JButton A40;
    public static javax.swing.JButton A50;
    public static javax.swing.JButton A60;
    public static javax.swing.JButton A70;
    public static javax.swing.JButton B01;
    public static javax.swing.JButton B11;
    public static javax.swing.JButton B21;
    public static javax.swing.JButton B31;
    public static javax.swing.JButton B41;
    public static javax.swing.JButton B51;
    public static javax.swing.JButton B61;
    public static javax.swing.JButton B71;
    public static javax.swing.JButton C02;
    public static javax.swing.JButton C12;
    public static javax.swing.JButton C22;
    public static javax.swing.JButton C32;
    public static javax.swing.JButton C42;
    public static javax.swing.JButton C52;
    public static javax.swing.JButton C62;
    public static javax.swing.JButton C72;
    public static javax.swing.JButton D03;
    public static javax.swing.JButton D13;
    public static javax.swing.JButton D23;
    public static javax.swing.JButton D33;
    public static javax.swing.JButton D43;
    public static javax.swing.JButton D53;
    public static javax.swing.JButton D63;
    public static javax.swing.JButton D73;
    public static javax.swing.JButton E04;
    public static javax.swing.JButton E14;
    public static javax.swing.JButton E24;
    public static javax.swing.JButton E34;
    public static javax.swing.JButton E44;
    public static javax.swing.JButton E54;
    public static javax.swing.JButton E64;
    public static javax.swing.JButton E74;
    public static javax.swing.JButton F05;
    public static javax.swing.JButton F15;
    public static javax.swing.JButton F25;
    public static javax.swing.JButton F35;
    public static javax.swing.JButton F45;
    public static javax.swing.JButton F55;
    public static javax.swing.JButton F65;
    public static javax.swing.JButton F75;
    public static javax.swing.JButton G06;
    public static javax.swing.JButton G16;
    public static javax.swing.JButton G26;
    public static javax.swing.JButton G36;
    public static javax.swing.JButton G46;
    public static javax.swing.JButton G56;
    public static javax.swing.JButton G66;
    public static javax.swing.JButton G76;
    public static javax.swing.JButton H07;
    public static javax.swing.JButton H17;
    public static javax.swing.JButton H27;
    public static javax.swing.JButton H37;
    public static javax.swing.JButton H47;
    public static javax.swing.JButton H57;
    public static javax.swing.JButton H67;
    public static javax.swing.JButton H77;
    public static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
